#!/bin/bash

#Websites directory
WEBSITES_DIR="/var/www/vhosts"

#Chown for host dir
CHOWN_HOST="prohfesor:web"

#Chmod for host dir
CHMOD_HOST='g+w'

#Server config dir
SERVER_CONF_DIR="/etc/httpd/conf.d"

#Server restart command
SERVER_RESTART="service httpd restart"