#!/bin/bash
c=${0%/*}/config ; source "$c" ; if [ $? -ne 0 ] ; then echo "Error: no config file $c" 1>&2 ; exit 1 ; fi

if [ -z "$1" ] ; then echo " Usage: new <host> " ; exit 1 ; fi

HOST=$1;
HOST_DIR="$WEBSITES_DIR/$HOST"

#copy files to host dir
cp -Rn ./template/host/* $HOST_DIR/

#fill files contents
grep -rl "\$HOST" $HOST_DIR | xargs sed -i s@"\$HOST"@$HOST@g

#chown host dir
echo " Change owner on host dir to: $CHOWN_HOST"
chown -R $CHOWN_HOST $HOST_DIR

#chmod host dir
echo " Change permissions on host dir to: $CHMOD_HOST"
chmod -R $CHMOD_HOST $HOST_DIR

#add config file to webserver
SERVER_CONF_FILE="$SERVER_CONF_DIR/$HOST.conf"
if [ -f $SERVER_CONF_FILE ]; then
    echo " Server conf $HOST.conf already exists!"
else
    echo " Adding config to server: $SERVER_CONF_FILE"
    cp ./template/server/host.conf $SERVER_CONF_FILE
fi
sed -i -e s@"\$HOST"@$HOST@g $SERVER_CONF_FILE
sed -i -e s@"\$WEBSITES_DIR"@$WEBSITES_DIR@g $SERVER_CONF_FILE

# REMEMBER TO RESTART SERVER !!!